name: 🛠️ Feature Request
description: Something can be improved/added
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature that could improve this project!

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Describe how it currently works
      placeholder: Explain the existing functionality
    validations:
      required: true

  - type: textarea
    id: desired-behavior
    attributes:
      label: Desired Behavior
      description: Describe how it should work
      placeholder: |
        Be sure to list:
        - acceptance
        - criteria
    validations:
      required: true

  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      description: Ideas on how to implement the addition or change (not obligatory)
      placeholder: Share your implementation thoughts if you have any

  - type: textarea
    id: context
    attributes:
      label: Context
      description: How has this issue affected you? What are you trying to accomplish?
      placeholder: Providing context helps us come up with a solution that is most useful in the real world
      
  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      options:
        - label: This feature request is estimated to be 1 workday or less, or I am going to break down this issue further with sub-issues.
          required: true 